<?php

class Pelanggan_model extends CI_Model {

	public function __construct()
	{
			$this->load->database();
	}

	public function get_pelanggan($slug = FALSE)
    {
        if ($slug === FALSE) 
        {
            $query = $this->db->get('pelanggan');
            return $query->result_array();
        }
        $this->db->select('*');
        $this->db->from('pelanggan');
        $this->db->where('slug', $slug);
        $this->db->or_where('chat_id', $slug);
        $this->db->or_where('username', $slug);
        $query = $this->db->get();
        return $query->row_array();
    }

    public function get_pelanggan_by_id($id = FALSE)
	{
		if ($id === FALSE) 
		{
			$query = $this->db->get('pelanggan');
			return $query->result_array();
		}
		$this->db->select('*');
        $this->db->from('pelanggan');
		$this->db->or_where('id_pelanggan', $id);
        $query = $this->db->get();
		return $query->row_array();
	}
    
	public function set_pelanggan()
    {
        $this->load->helper('url');
        $slug = url_title($this->input->post('no_identitas'), 'dash', TRUE);
        
        $data = array(
            'nama' => $this->input->post('nama'),
            'no_identitas' => $this->input->post('no_identitas'),
            'chat_id' => $this->input->post('chat_id'),
            'username' => $this->input->post('username'),
            'slug' => $slug
        );

        $this->db->insert('pelanggan', $data);
        $insert_id = $this->db->insert_id();
        $message = [
            'id' => $insert_id, // Automatically generated by the model
            'message' => 'Added a resource'
        ];
       

    }

    public function edit_pelanggan_by_webhook($id, $data)
    {
        $this->db->where('chat_id', $id);
        $this->db->set($data);
        $this->db->update('pelanggan');
    }

}